################################# Default configuration ###################
baseURL = "http://ochiailab.netlify.app"
title = "Ochiai Laboratory"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

# [params.widgets]
# sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo1.png"
# Meta data
description = "Welcome to Ochiai Laboratory"
author = "Tianji Shen"
# Contact Information
phone = "(+81)80-6887-4315"
# email = "demo@email.com"
location = "Room 809 Department of Electronic and Computer Engineering, Yokohama National University, 79-5 Tokiwadai, Hodogaya-ku, Yokohama, Kanagawa, 240-8501 Japan"
# contact form action
# contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "../images/convent.gif" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

  
############################# social site ########################
# [[params.social]]
# icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
# copyright
copyright = "Copyright &copy; 2020 [Ochiailab](https://www.ochiailab.dnj.ynu.ac.jp) All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Research"
URL = "research"
weight = 2

[[Languages.en.menu.main]]
name = "Members"
URL = "members"
weight = 3

[[Languages.en.menu.main]]
name = "Achievements"
weight = 4
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Achievements"
  name = "Int. Publications"
  URL = "international"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Achievements"
  name = "Dom. Publications"
  URL = "domestic"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "Achievements"
  name = "Award"
  URL = "award"
  weight = 3


[[Languages.en.menu.main]]
name = "News"
URL = "news"
weight = 5
  
[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 6

[[Languages.en.menu.main]]
name = "Super-Mjograph"
URL = "https://www.mjograph.net/"
weight = 7

[[Languages.en.menu.main]]
name = "Wiki (Only for members)"
URL = "https://sites.google.com/a/ochiailab.com/wiki/"
weight = 8
# footer menu
# [[Languages.en.menu.footer]]
# name = "Research"
# URL = "about"
# weight = 1

# [[Languages.en.menu.footer]]
# name = "Members"
# URL = "members"
# weight = 2

# [[Languages.en.menu.footer]]
# name = "Domestic Publications"
# URL = "domestic"
# weight = 3

# [[Languages.en.menu.footer]]
# name = "International Publications"
# URL = "international"
# weight = 4

# [[Languages.en.menu.footer]]
# name = "News"
# URL = "news"
# weight = 5

# [[Languages.en.menu.footer]]
# name = "Contact"
# URL = "contact"
# weight = 6

################################ Japanese Language ########################
[Languages.jp]
languageName = "Jp"
languageCode = "jp-ja"
contentDir = "content/japanese"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 [Ochiailab](https://www.ochiailab.dnj.ynu.ac.jp) All Rights Reserved"


######################### japanese navigation #############################
# main menu
[[Languages.jp.menu.main]]
name = "ホーム"
URL = "/"
weight = 1

[[Languages.jp.menu.main]]
name = "研究"
URL = "research"
weight = 2

[[Languages.jp.menu.main]]
name = "メンバー"
URL = "members"
weight = 3

[[Languages.jp.menu.main]]
name = "研究実績"
weight = 4
hasChildren = true


  [[Languages.jp.menu.main]]
  URL = "international"
  name = "国際発表"
  parent = "研究実績"
  weight = 1

  [[Languages.jp.menu.main]]
  URL = "domestic"
  name = "国内発表"
  parent = "研究実績"
  weight = 2

  [[Languages.jp.menu.main]]
  URL = "award"
  name = "受賞"
  parent = "研究実績"
  weight = 3

[[Languages.jp.menu.main]]
name = "ニュース"
URL = "news"
weight = 5
  
[[Languages.jp.menu.main]]
name = "お問い合わせ"
URL = "contact"
weight = 6

[[Languages.jp.menu.main]]
name = "Super-Mjograph"
URL = "https://www.mjograph.net/"
weight = 7


# footer menu
# [[Languages.jp.menu.footer]]
# name = "研究テーマ"
# URL = "research"
# weight = 1

#[[Languages.jp.menu.footer]]
#name = "メンバー"
#URL = "members"
#weight = 2

#[[Languages.jp.menu.footer]]
#name = "国内発表"
#URL = "domestic"
#weight = 3

#[[Languages.jp.menu.footer]]
#name = "国際発表"
#URL = "international"
#weight = 4

#[[Languages.jp.menu.footer]]
#name = "ニュース"
#URL = "news"
#weight = 5

#[[Languages.jp.menu.footer]]
#name = "お問い合わせ"
#URL = "contact"
#weight = 6